### ISSUE TITLE
Warzone / MW / Vanguard

### ISSUE THREAD

**Issue by Nou4r** [dword64/Ow-Anti-Flag#1]
Could i hire you to look into warzones identifiation system? I've used this with spoofer that spoofs disk, mb, ram and perm mac but no luck sadly. It fixed my battle.net ban tho so thanks a lot for that!

**Comment by dword64** [comment]
> Could i hire you to look into warzones identifiation system? I've used this with spoofer that spoofs disk, mb, ram and perm mac but no luck sadly. It fixed my battle.net ban tho so thanks a lot for that!

Hey! You mean a kind of AntiFlag version for the Call of Duty series?

**Comment by Nou4r** [comment]
Yes something like that unless they need SMBIOS to be spoofed of Course

**Comment by dword64** [comment]
@Nou4r Aight! we will take a look and come back to you at a later point! merry xmas and stay safe!

**Comment by LVYC032** [comment]
你好，这个是《overwatch》作弊工具吗？我应该如何使用它

**Comment by AVISIX** [comment]
> 

![image](https://user-images.githubusercontent.com/54699751/148091381-21c5b8cb-8167-4f16-9eca-a9ff58c4db7c.png)

**Comment by dword64** [comment]
@LVYC032 仅限英语

**Comment by dword64** [comment]
New repo will be opened for it
