### ISSUE TITLE
Xbox One Use

### ISSUE THREAD

**Issue by Ruxty2000** [dword64/Ow-Anti-Flag#3]
Hi, I used the anti flag on my PC recently and it worked like a dream, however, I keep getting chain banned on my xbox one and would like to play OW on my xbox one without getting my main banned. Is there a way to use this on xbox or not, or is the ban done through which xbox profile it is linked to? If not, is there any way to prevent chain bans on the xbox, such as hard resetting my xbox one, which I do not mind doing. Thanks.

**Comment by guildnie** [comment]
您发给我的信件已经收到，非常感谢。我们将在未来可期的时间内与您沟通。再次感谢您对我们的长期关注***********************This is Automatic reply.
    If you rec

**Comment by dword64** [comment]
> Hi, I used the anti flag on my PC recently and it worked like a dream, however, I keep getting chain banned on my xbox one and would like to play OW on my xbox one without getting my main banned. Is there a way to use this on xbox or not, or is the ban done through which xbox profile it is linked to? If not, is there any way to prevent chain bans on the xbox, such as hard resetting my xbox one, which I do not mind doing. Thanks.


@Ruxty2000 it's only meant for using it on Computers, sorry.
