### ISSUE TITLE
Is it still working?

### ISSUE THREAD

**Issue by SaeedNassar** [dword64/Ow-Anti-Flag#4]
Is it still working and ud?

**Comment by guildnie** [comment]
您发给我的信件已经收到，非常感谢。我们将在未来可期的时间内与您沟通。再次感谢您对我们的长期关注***********************This is Automatic reply.
    If you rec

**Comment by dword64** [comment]
Firstly it can be detected? Secondly idk, stop pushing updates since some people are stealing the source without giving credits ;D @GamingMazen

**Comment by ghost** [comment]
> Firstly it can be detected? Secondly idk, stop pushing updates since some people are stealing the source without giving credits ;D @GamingMazen

Call them out in the readme so we know who to raise our pitchforks at.

**Comment by dword64** [comment]
> > Firstly it can be detected? Secondly idk, stop pushing updates since some people are stealing the source without giving credits ;D @GamingMazen
> 
> Call them out in the readme so we know who to raise our pitchforks at.

https://github.com/Avalon-Group/Ghost-Overwatch-Source 

@EvilEpicPanda Sadly the owner dropped a dmca but already did it. Will re-upload it later
