### ISSUE TITLE
Can you update the release version,thx!

### ISSUE THREAD

**Issue by GhostX123** [dword64/Ow-Anti-Flag#6]
I've seen an update recently,but i don't know how to build,i hope you can update the latest version plz,thx a lot!

**Comment by guildnie** [comment]
您发给我的信件已经收到，非常感谢。我们将在未来可期的时间内与您沟通。再次感谢您对我们的长期关注***********************This is Automatic reply.
    If you rec

**Comment by Nou4r** [comment]
Project is obviously abandoned, truly a shame.

**Comment by dword64** [comment]
> Project is obviously abandoned, truly a shame.

@Nou4r Feel free to contribute, reverse Overwatch and its modules. Open a pull request with your changes. 😄 Neither Six nor I will be working on the project any longer.

**Comment by guildnie** [comment]
您发给我的信件已经收到，非常感谢。我们将在未来可期的时间内与您沟通。再次感谢您对我们的长期关注***********************This is Automatic reply.
    If you rec
