### ISSUE TITLE
Update covering the new HWID ban launched around October 2023

### ISSUE THREAD

**Issue by nlamarque42** [dword64/Ow-Anti-Flag#7]
**Is your feature request related to a problem? Please describe.**
I've encountered a significant issue with the recent implementation of HWID bans by Warden in Overwatch. Previously, the Anti-Flag tool was highly effective in circumventing IP bans, provided the right parallel measures were in place. However, with the introduction of a new, sophisticated HWID ban system, the landscape has changed dramatically. The challenge now is that Warden's HWID bans are so effective that they automatically ban any new account within 24-48 hours, rendering traditional anti-flag measures ineffective.

**Describe the solution you'd like**
I propose the development of an advanced solution within the Anti-Flag tool to effectively spoof these new HWID bans. The current methods, including classic HWID spoofing techniques such as Revo, volumeid, Cryptography, UUID, MAC, VPNs, and even external devices, have proven futile against Overwatch's system. A comprehensive approach is needed, possibly involving an in-depth analysis and countermeasure for the registry entries or system files that Overwatch or Battle.net might be using to identify hardware.

**Describe alternatives you've considered**
One drastic alternative that has worked is completely formatting hard disks and reinstalling Windows. However, this method is extremely cumbersome and not practical for most users. I believe there's a more user-friendly solution that can be integrated into the Anti-Flag tool.

**Additional context**
I strongly suspect that the ban information is stored in a special registry or system file indirectly linked to Overwatch or Battle.net, but identifying the exact location and nature of these files is the key challenge. If anyone within the Avalon Group or the community has more precise information about Warden's HWID ban method or potential workarounds, your input would be immensely valuable.

**Comment by nlamarque42** [comment]
Ok my bad I just saw you stopped working on that project. I will use my own brain cells.

**Comment by dword64** [comment]
@Ashitaka06 FYI, whoever told you that Overwatch bans HWIDs is not proficient at reversing. Overwatch has not implemented HWID bans; they still rely on SWID. The only improvement they've made is in server-sided checks for various factors like suspicious SMS, emails, and more. Therefore, strategies such as changing phone numbers, running anti-flag measures, altering your network adapter's MAC addresses, and using a VPN each time you switch accounts can be effective. I appreciate the clear feature request, but unfortunately, I won't be working on it publicly anymore. This decision stems from past and ongoing incidents where people have copied our work without giving credit or even sold it, despite it being free to use. If you share your Discord username, I might be able to assist you. ;D feel free to contribute tho

> Ok my bad I just saw you stopped working on that project. I will use my own brain cells.

**Comment by nlamarque42** [comment]
Thank you for your reply my friend, for the record I was the only one to convince myself that there was a HWID ban because my bans had all the symptoms. But I omitted the SWID ban solution because I was too lazy to reverse.

I discovered your work yesterday and decided to stop relying on other UC pasters and use my own brain to solve my problems. 
I will make a clear & useful contribution when I have solved the problem (which I think I already did, still need to confirm by getting no ban in a week).

Thanks again for the work you have been able to do in the past for this community and I will continue to follow your (and AVISIX) achievements very closely. Take care!

**Comment by dword64** [comment]
<3, you can leave this open for future questions or sharing progress

> Thank you for your reply my friend, for the record I was the only one to convince myself that there was a HWID ban because my bans had all the symptoms. But I omitted the SWID ban solution because I was too lazy to reverse.
> 
> I discovered your work yesterday and decided to stop relying on other UC pasters and use my own brain to solve my problems. I will make a clear & useful contribution when I have solved the problem (which I think I already did, still need to confirm by getting no ban in a week).
> 
> Thanks again for the work you have been able to do in the past for this community and I will continue to follow your (and AVISIX) achievements very closely. Take care!

**Comment by nlamarque42** [comment]
Ok it's so dumb, I just did a manual check by isolating the part where regs are supposed to be deleted in Overwatch.hpp.
If you don't run _REGDEL("HKEY_CLASSES_ROOT\\Applications\\Overwatch.exe");_ in Admin mode, it will do absolutely nothing and will not raise any Exception.
However, in Admin mode, it's working as intended.
So maybe add: "Just run it **as Administrator**, that's it really." in the 'How to Use ?' section of *README* to avoid stupid people like me declaring that Anti-Flag is deprecated.

Attached .zip file with ccp so you can state this by yourself with & without Admin.
[testing_REGDEL.zip](https://github.com/dword64/Ow-Anti-Flag/files/13601983/testing_REGDEL.zip)

Anyways, bye! <3 **(still SWID/IP and not HWID 100% confirmed after 7 days test)**

**Comment by nlamarque42** [comment]
Additional Note: On my computer, Anti-Flag could be executed without Administrator rights but on another VM, it does require them. Weird af, that was mostly the reason why it was not effective.

**Comment by dword64** [comment]
Sorry i do not download a zip file from Strangers ;D Yet it requests Admin permissions see here -> https://github.com/dword64/Ow-Anti-Flag/blob/22e9e06d270f6935ab3c5a6273647e9b14162ff1/Anti-Flag/Anti-Flag.vcxproj#L154

**Comment by dword64** [comment]
You've to build it on Release mode not for Debug :D

**Comment by dword64** [comment]
> Ok it's so dumb, I just did a manual check by isolating the part where regs are supposed to be deleted in Overwatch.hpp. If you don't run _REGDEL("HKEY_CLASSES_ROOT\Applications\Overwatch.exe");_ in Admin mode, it will do absolutely nothing and will not raise any Exception. However, in Admin mode, it's working as intended. So maybe add: "Just run it **as Administrator**, that's it really." in the 'How to Use ?' section of _README_ to avoid stupid people like me declaring that Anti-Flag is deprecated.
> 
> Attached .zip file with ccp so you can state this by yourself with & without Admin. [testing_REGDEL.zip](https://github.com/dword64/Ow-Anti-Flag/files/13601983/testing_REGDEL.zip)
> 
> Anyways, bye! <3 **(still SWID/IP and not HWID 100% confirmed after 7 days test)**

Glad to hear
